# Generated by Django 3.2.6 on 2021-09-06 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='room',
        ),
    ]
