# Generated by Django 3.2.7 on 2021-09-08 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_auto_20210908_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='type_of_room',
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='rooms.roomtype'),
        ),
        migrations.AlterField(
            model_name='room',
            name='instant_book',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='TypeOfRoom',
        ),
    ]
