# Generated by Django 3.2.6 on 2021-09-01 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('review', models.TextField()),
                ('accuracy', models.IntegerField(default=5)),
                ('communication', models.IntegerField(default=5)),
                ('cleanliness', models.IntegerField(default=5)),
                ('location', models.IntegerField(default=5)),
                ('check_in', models.IntegerField(default=5)),
                ('value', models.IntegerField(default=5)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
